"""add_operator_name_to_lightstrip

Revision ID: 4c3730bc904a
Revises: c37325e30440
Create Date: 2025-03-07 13:51:46.566575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3730bc904a'
down_revision = 'c37325e30440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('light_strip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('light_strip', schema=None) as batch_op:
        batch_op.drop_column('operator_name')

    # ### end Alembic commands ###
